#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/share/xunlei/xunlei

get_config() {
	config_get_bool enabled $1 enabled 0
	config_get internal $1 internal 1
	config_get port $1 port 5051
	config_get config_path $1 config_path "/var/packages/pan-xunlei-com"
	config_get download_path $1 download_dir "/tmp/downloads"
}

start_service() {
	config_load xunlei
	config_foreach get_config xunlei
	[ $enabled -ne 1 ] && return 1

	procd_open_instance
	procd_set_param command $PROG
	procd_append_param command launch -i $internal -p $port -d $download_dir -c $download_path
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "xunlei"
}

reload_service() {
	stop
	sleep 3
	start
}
